---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast
      - id: check-merge-conflict
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.670-1
    hooks:
      - id: mypy
  - repo: https://github.com/thelonelyghost/pre-commit-isort
    rev: v4.3.17
    hooks:
      - id: isort-pyproject
