---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: trailing-whitespace
        stages: ['push']
      - id: end-of-file-fixer
        stages: ['push']
      - id: check-yaml
        stages: ['commit']
      - id: check-ast
        stages: ['commit']
      - id: check-merge-conflict
        stages: ['commit']
      - id: check-added-large-files
        stages: ['commit']
  - repo: https://github.com/thelonelyghost/pre-commit-python
    rev: v0.1.0
    hooks:
      - id: isort
        args: ['--settings-path=./pyproject.toml']
        stages: ['push']
      - id: mypy
        stages: ['push']
      - id: black-fmt
        stages: ['push']
  - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    sha: v1.0.0
    hooks:
      - id: rst-linter
        stages: ['commit']
